import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import html2canvas from 'html2canvas';
import { format } from 'date-fns';
import {
  generateAnalyticsFilename,
  buildExecutiveSummary,
  type ExecutiveSummaryInput,
} from '@/lib/analyticsExport';

export interface AnalyticsPdfPayload {
  periodLabel: string;
  generatedBy: { name: string; role: string };
  summary: ExecutiveSummaryInput & {
    overallActivityRate: string;
    factoryComplianceRate: string;
    meetingFrequencyThisMonth: string;
    openTaskCount: number;
    overdueTaskCount: number;
  };
  peopleStatusBreakdown: { active: number; idle: number; inactive: number; never: number };
  peopleRows: Array<{
    name: string; role: string; depts: string;
    lastActivity: string; score: number; status: string;
  }>;
  complianceRows: Array<{
    name: string; expected: number; actual: number;
    compliance: number; late: number; lastEntry: string;
  }>;
  meetingRows: Array<{
    date: string; title: string; status: string; attendance: string;
    tasks: number; notes: string; decisions: string;
  }>;
  taskHealthRows: Array<{
    name: string; open: number; overdue: number; completionRate: number;
    avgDays: number; pushbacks: number; lastActivity: string;
  }>;
}

const MARGIN = 14;

function addCoverPage(doc: jsPDF, payload: AnalyticsPdfPayload) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('ITC PPB NPF', pageW / 2, pageH / 2 - 30, { align: 'center' });
  doc.setFontSize(16);
  doc.text('Platform Analytics Report', pageW / 2, pageH / 2 - 18, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  const lines = [
    `Period: ${payload.periodLabel}`,
    `Generated: ${format(new Date(), 'd MMM yyyy, HH:mm')}`,
    `Generated by: ${payload.generatedBy.name} (${payload.generatedBy.role})`,
  ];
  lines.forEach((l, i) => {
    doc.text(l, pageW / 2, pageH / 2 + i * 8, { align: 'center' });
  });

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text('Confidential — For Internal Use Only', pageW / 2, pageH - 20, { align: 'center' });
  doc.setTextColor(0);
}

function addSectionTitle(doc: jsPDF, title: string, y = MARGIN) {
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN, y);
  doc.setFont('helvetica', 'normal');
  return y + 6;
}

function addExecutiveSummary(doc: jsPDF, payload: AnalyticsPdfPayload) {
  doc.addPage('p');
  let y = addSectionTitle(doc, 'Executive Summary');

  const summary = buildExecutiveSummary(payload.summary);

  // Signal alerts block
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Non-compliance signals', MARGIN, y); y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  const signalLines: Array<[string, string]> = [
    [
      `Users inactive 14+ days (${summary.inactiveUsers.length})`,
      summary.inactiveUsers.slice(0, 12).map((u) => u.name).join(', ') || 'None',
    ],
    [
      `Departments below 50% KPI compliance (${summary.lowComplianceDepts.length})`,
      summary.lowComplianceDepts
        .map((d) => `${d.name} (${d.compliance}%)`).join(', ') || 'None',
    ],
    [
      `Tasks with 3+ due-date pushbacks (${summary.pushbackTasks.length})`,
      summary.pushbackTasks.slice(0, 12).map((t) => t.title).join(', ') || 'None',
    ],
    [
      'Meetings with no tasks created (last 7 days)',
      String(summary.zeroTaskMeetingsThisWeek),
    ],
  ];

  signalLines.forEach(([label, detail]) => {
    doc.setFont('helvetica', 'bold');
    const labelLines = doc.splitTextToSize(`• ${label}`, 180);
    doc.text(labelLines, MARGIN, y);
    y += labelLines.length * 5;
    doc.setFont('helvetica', 'normal');
    const detailLines = doc.splitTextToSize(detail, 175);
    doc.text(detailLines, MARGIN + 4, y);
    y += detailLines.length * 5 + 3;
  });

  y += 4;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Key metrics', MARGIN, y); y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  const stats: Array<[string, string]> = [
    ['Overall platform activity', payload.summary.overallActivityRate],
    ['Factory KPI compliance', payload.summary.factoryComplianceRate],
    ['Meeting frequency this month', payload.summary.meetingFrequencyThisMonth],
    [
      'Open / overdue tasks',
      `${payload.summary.openTaskCount} open, ${payload.summary.overdueTaskCount} overdue`,
    ],
  ];
  stats.forEach(([label, value]) => {
    doc.text(`${label}: `, MARGIN, y);
    doc.setFont('helvetica', 'bold');
    doc.text(value, MARGIN + 70, y);
    doc.setFont('helvetica', 'normal');
    y += 6;
  });
}

function addPeoplePage(doc: jsPDF, payload: AnalyticsPdfPayload) {
  doc.addPage('p');
  let y = addSectionTitle(doc, 'People & Engagement');
  const b = payload.peopleStatusBreakdown;
  doc.setFontSize(10);
  doc.text(
    `Active: ${b.active}    Idle: ${b.idle}    Inactive: ${b.inactive}    Never: ${b.never}`,
    MARGIN, y,
  );
  y += 4;

  autoTable(doc, {
    startY: y,
    head: [['User', 'Role', 'Departments', 'Last Activity', 'Score', 'Status']],
    body: payload.peopleRows.map((r) => [
      r.name, r.role, r.depts, r.lastActivity, String(r.score), r.status,
    ]),
    styles: { fontSize: 8, cellPadding: 1.5 },
    headStyles: { fillColor: [60, 60, 60] },
    margin: { left: MARGIN, right: MARGIN },
  });
}

async function captureChart(selector: string): Promise<string | null> {
  const el = document.querySelector<HTMLElement>(`[data-export-chart="${selector}"]`);
  if (!el) return null;
  try {
    const canvas = await html2canvas(el, { backgroundColor: '#ffffff', scale: 2 });
    return canvas.toDataURL('image/png');
  } catch {
    return null;
  }
}

async function addCompliancePage(doc: jsPDF, payload: AnalyticsPdfPayload) {
  doc.addPage('p');
  addSectionTitle(doc, 'KPI Compliance');
  autoTable(doc, {
    startY: MARGIN + 4,
    head: [['Department', 'Expected', 'Actual', 'Compliance %', 'Late', 'Last Entry']],
    body: payload.complianceRows.map((r) => [
      r.name, String(r.expected), String(r.actual),
      `${r.compliance}%`, String(r.late), r.lastEntry,
    ]),
    styles: { fontSize: 9, cellPadding: 2 },
    headStyles: { fillColor: [60, 60, 60] },
    margin: { left: MARGIN, right: MARGIN },
  });

  const chart = await captureChart('compliance-chart');
  if (chart) {
    doc.addPage('l');
    addSectionTitle(doc, 'KPI Compliance — Weekly Trend');
    const pageW = doc.internal.pageSize.getWidth();
    const w = pageW - MARGIN * 2;
    const h = w * 0.5;
    doc.addImage(chart, 'PNG', MARGIN, MARGIN + 6, w, h);
  }
}

async function addMeetingPage(doc: jsPDF, payload: AnalyticsPdfPayload) {
  const chart = await captureChart('meeting-frequency-chart');
  if (chart) {
    doc.addPage('l');
    addSectionTitle(doc, 'Meeting Health — Frequency');
    const pageW = doc.internal.pageSize.getWidth();
    const w = pageW - MARGIN * 2;
    const h = w * 0.4;
    doc.addImage(chart, 'PNG', MARGIN, MARGIN + 6, w, h);
  }
  doc.addPage('p');
  addSectionTitle(doc, 'Meeting Quality (last 20)');
  autoTable(doc, {
    startY: MARGIN + 4,
    head: [['Date', 'Title', 'Status', 'Attendance', 'Tasks', 'Notes', 'Decisions']],
    body: payload.meetingRows.map((r) => [
      r.date, r.title, r.status, r.attendance, String(r.tasks), r.notes, r.decisions,
    ]),
    styles: { fontSize: 8, cellPadding: 1.5 },
    headStyles: { fillColor: [60, 60, 60] },
    margin: { left: MARGIN, right: MARGIN },
  });
}

async function addTaskPage(doc: jsPDF, payload: AnalyticsPdfPayload) {
  doc.addPage('p');
  addSectionTitle(doc, 'Task Accountability');
  autoTable(doc, {
    startY: MARGIN + 4,
    head: [['Assignee', 'Open', 'Overdue', 'Completion %', 'Avg Days', 'Pushbacks', 'Last Activity']],
    body: payload.taskHealthRows.map((r) => [
      r.name, String(r.open), String(r.overdue), `${r.completionRate}%`,
      String(r.avgDays), String(r.pushbacks), r.lastActivity,
    ]),
    styles: { fontSize: 9, cellPadding: 2 },
    headStyles: { fillColor: [60, 60, 60] },
    margin: { left: MARGIN, right: MARGIN },
  });

  const chart = await captureChart('overdue-trend-chart');
  if (chart) {
    doc.addPage('l');
    addSectionTitle(doc, 'Overdue Tasks — Weekly Trend');
    const pageW = doc.internal.pageSize.getWidth();
    const w = pageW - MARGIN * 2;
    const h = w * 0.4;
    doc.addImage(chart, 'PNG', MARGIN, MARGIN + 6, w, h);
  }
}

export async function exportAnalyticsPdf(payload: AnalyticsPdfPayload): Promise<string> {
  const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
  addCoverPage(doc, payload);
  addExecutiveSummary(doc, payload);
  addPeoplePage(doc, payload);
  await addCompliancePage(doc, payload);
  await addMeetingPage(doc, payload);
  await addTaskPage(doc, payload);

  const filename = generateAnalyticsFilename(new Date());
  doc.save(filename);
  return filename;
}
